apiVersion: v1
kind: Service
metadata:
  name: booking
spec:
  selector:
    app.kubernetes.io/name: booking
    app.kubernetes.io/version: "0.1.0"
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: skyline
  ports:
    - name: http
      port: 80
      targetPort: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: booking
  labels:
    name: booking
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: booking
      app.kubernetes.io/version: "0.1.0"
      app.kubernetes.io/component: backend
      app.kubernetes.io/part-of: skyline
  template:
    metadata:
      labels:
        app.kubernetes.io/name: booking
        app.kubernetes.io/version: "0.1.0"
        app.kubernetes.io/component: backend
        app.kubernetes.io/part-of: skyline
    spec:
      containers:
        - name: booking
          image: idos2002/skyline-booking:0.1.0
          envFrom:
            - configMapRef:
                name: booking-config
                optional: false
          env:
            - name: SKYLINE_ACCESS_TOKEN_SECRET
              valueFrom:
                secretKeyRef:
                  name: access-token-secret
                  key: access_token_secret
            - name: SKYLINE_PNR_DB_URI
              valueFrom:
                secretKeyRef:
                  name: pnr-db-secret
                  key: full_db_uri
                  optional: false
            - name: SKYLINE_PNR_DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: pnr-db-config
                  key: db_name
                  optional: false
            - name: SKYLINE_PNR_DB_COLLECTION_NAME
              valueFrom:
                configMapKeyRef:
                  name: pnr-db-config
                  key: pnr_collection_name
            - name: SKYLINE_INVENTORY_MANAGER_URL
              valueFrom:
                configMapKeyRef:
                  name: inventory-manager-config
                  key: graphql_api_url
                  optional: false
            - name: SKYLINE_RABBITMQ_URI
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: full_uri
                  optional: false
            - name: SKYLINE_TICKET_EXCHANGE_NAME
              valueFrom:
                configMapKeyRef:
                  name: rabbitmq-config
                  key: ticket_exchange_name
                  optional: false
            - name: SKYLINE_TICKET_BOOKING_ROUTING_KEY
              valueFrom:
                configMapKeyRef:
                  name: rabbitmq-config
                  key: ticket_booking_routing_key
                  optional: false
            - name: SKYLINE_EMAIL_EXCHANGE_NAME
              valueFrom:
                configMapKeyRef:
                  name: rabbitmq-config
                  key: email_exchange_name
                  optional: false
            - name: SKYLINE_EMAIL_BOOKING_CONFIRMATION_ROUTING_KEY
              valueFrom:
                configMapKeyRef:
                  name: rabbitmq-config
                  key: email_booking_confirmation_routing_key
                  optional: false
            - name: SKYLINE_EMAIL_BOOKING_CANCELLATION_ROUTING_KEY
              valueFrom:
                configMapKeyRef:
                  name: rabbitmq-config
                  key: email_booking_cancellation_routing_key
                  optional: false
            - name: SKYLINE_EMAIL_BOARDING_PASS_ROUTING_KEY
              valueFrom:
                configMapKeyRef:
                  name: rabbitmq-config
                  key: email_boarding_pass_routing_key
                  optional: false
          ports:
            - name: http
              containerPort: 80
