apiVersion: v1
kind: Service
metadata:
  name: email
spec:
  selector:
    app.kubernetes.io/name: email
    app.kubernetes.io/version: "0.1.0"
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: skyline
  ports:
    - name: http
      port: 80
      targetPort: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: email
  labels:
    name: email
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: email
      app.kubernetes.io/version: "0.1.0"
      app.kubernetes.io/component: backend
      app.kubernetes.io/part-of: skyline
  template:
    metadata:
      labels:
        app.kubernetes.io/name: email
        app.kubernetes.io/version: "0.1.0"
        app.kubernetes.io/component: backend
        app.kubernetes.io/part-of: skyline
    spec:
      containers:
        - name: email
          image: idos2002/skyline-email:0.1.0
          envFrom:
            - configMapRef:
                name: email-config
                optional: false
          env:
            - name: SKYLINE_RABBITMQ_URI
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: full_uri
                  optional: false
            - name: SKYLINE_EMAIL_EXCHANGE_NAME
              valueFrom:
                configMapKeyRef:
                  name: rabbitmq-config
                  key: email_exchange_name
                  optional: false
            - name: SKYLINE_EMAIL_QUEUE_NAME
              valueFrom:
                configMapKeyRef:
                  name: rabbitmq-config
                  key: email_queue_name
                  optional: false
            - name: SKYLINE_EMAIL_BINDING_KEY
              valueFrom:
                configMapKeyRef:
                  name: rabbitmq-config
                  key: email_binding_key
                  optional: false
            - name: SKYLINE_EMAIL_BOOKING_CONFIRMATION_MESSAGE_TYPE
              valueFrom:
                configMapKeyRef:
                  name: rabbitmq-config
                  key: email_booking_confirmation_routing_key
                  optional: false
            - name: SKYLINE_EMAIL_FLIGHT_TICKET_MESSAGE_TYPE
              valueFrom:
                configMapKeyRef:
                  name: rabbitmq-config
                  key: email_ticket_routing_key
                  optional: false
            - name: SKYLINE_EMAIL_BOOKING_CANCELLATION_MESSAGE_TYPE
              valueFrom:
                configMapKeyRef:
                  name: rabbitmq-config
                  key: email_booking_cancellation_routing_key
                  optional: false
            - name: SKYLINE_EMAIL_BOARDING_PASS_MESSAGE_TYPE
              valueFrom:
                configMapKeyRef:
                  name: rabbitmq-config
                  key: email_boarding_pass_routing_key
                  optional: false
            - name: SKYLINE_DEAD_LETTER_EXCHANGE_NAME
              valueFrom:
                configMapKeyRef:
                  name: rabbitmq-config
                  key: dead_letter_exchange_name
                  optional: false
            - name: SKYLINE_DEAD_LETTER_ROUTING_KEY
              valueFrom:
                configMapKeyRef:
                  name: rabbitmq-config
                  key: dead_letter_email_routing_key
                  optional: false
            - name: SKYLINE_PNR_DB_URI
              valueFrom:
                secretKeyRef:
                  name: pnr-db-secret
                  key: full_db_uri
                  optional: false
            - name: SKYLINE_PNR_DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: pnr-db-config
                  key: db_name
                  optional: false
            - name: SKYLINE_PNR_DB_COLLECTION_NAME
              valueFrom:
                configMapKeyRef:
                  name: pnr-db-config
                  key: pnr_collection_name
            - name: SKYLINE_INVENTORY_MANAGER_URL
              valueFrom:
                configMapKeyRef:
                  name: inventory-manager-config
                  key: graphql_api_url
                  optional: false
            - name: SKYLINE_EMAIL_ADDRESS
              valueFrom:
                secretKeyRef:
                  name: email-secret
                  key: email_address
                  optional: false
            - name: SKYLINE_SMTP_HOST
              valueFrom:
                secretKeyRef:
                  name: email-secret
                  key: smtp_host
                  optional: false
            - name: SKYLINE_SMTP_PORT
              valueFrom:
                secretKeyRef:
                  name: email-secret
                  key: smtp_port
                  optional: false
            - name: SKYLINE_SMTP_USERNAME
              valueFrom:
                secretKeyRef:
                  name: email-secret
                  key: username
                  optional: false
            - name: SKYLINE_SMTP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: email-secret
                  key: password
                  optional: false
          ports:
            - name: http
              containerPort: 80
