apiVersion: v1
kind: Service
metadata:
  name: flights
spec:
  selector:
    app.kubernetes.io/name: flights
    app.kubernetes.io/version: "0.1.0"
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: skyline
  ports:
    - name: http
      port: 80
      targetPort: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flights
  labels:
    name: flights
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: flights
      app.kubernetes.io/version: "0.1.0"
      app.kubernetes.io/component: backend
      app.kubernetes.io/part-of: skyline
  template:
    metadata:
      labels:
        app.kubernetes.io/name: flights
        app.kubernetes.io/version: "0.1.0"
        app.kubernetes.io/component: backend
        app.kubernetes.io/part-of: skyline
    spec:
      containers:
        - name: flights
          image: idos2002/skyline-flights:0.1.0
          envFrom:
            - configMapRef:
                name: flights-config
                optional: false
          env:
            - name: SKYLINE_INVENTORY_MANAGER_URL
              valueFrom:
                configMapKeyRef:
                  name: inventory-manager-config
                  key: graphql_api_url
                  optional: false
          ports:
            - name: http
              containerPort: 80
