apiVersion: v1
kind: Service
metadata:
  name: inventory-manager
spec:
  selector:
    app.kubernetes.io/name: inventory-manager
    app.kubernetes.io/version: "0.1.0"
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: skyline
  ports:
    - name: http
      port: 80
      targetPort: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-manager
  labels:
    name: inventory-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: inventory-manager
      app.kubernetes.io/version: "0.1.0"
      app.kubernetes.io/component: backend
      app.kubernetes.io/part-of: skyline
  template:
    metadata:
      labels:
        app.kubernetes.io/name: inventory-manager
        app.kubernetes.io/version: "0.1.0"
        app.kubernetes.io/component: backend
        app.kubernetes.io/part-of: skyline
    spec:
      containers:
        - name: inventory-manager
          image: idos2002/skyline-inventory-manager:0.1.0
          env:
            - name: HASURA_GRAPHQL_DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: inventory-db-secret
                  key: full_db_uri
                  optional: false
            - name: HASURA_GRAPHQL_ADMIN_SECRET
              valueFrom:
                secretKeyRef:
                  name: inventory-manager-secret
                  key: admin_secret
                  optional: false
            - name: HASURA_GRAPHQL_UNAUTHORIZED_ROLE
              valueFrom:
                configMapKeyRef:
                  name: inventory-manager-config
                  key: unauthorized_role
                  optional: false
            - name: HASURA_GRAPHQL_SERVER_PORT
              valueFrom:
                configMapKeyRef:
                  name: inventory-manager-config
                  key: port
                  optional: false
            - name: HASURA_GRAPHQL_ENABLE_CONSOLE
              valueFrom:
                configMapKeyRef:
                  name: inventory-manager-config
                  key: enable_console
            - name: HASURA_GRAPHQL_ENABLED_LOG_TYPES
              valueFrom:
                configMapKeyRef:
                  name: inventory-manager-config
                  key: enabled_log_types
          ports:
            - name: http
              containerPort: 80
