apiVersion: v1
kind: Service
metadata:
  name: inventory-db
spec:
  selector:
    app.kubernetes.io/name: inventory-db
    app.kubernetes.io/version: "0.1.0"
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: skyline
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-db
  labels:
    name: inventory-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: inventory-db
      app.kubernetes.io/version: "0.1.0"
      app.kubernetes.io/component: database
      app.kubernetes.io/part-of: skyline
  template:
    metadata:
      labels:
        app.kubernetes.io/name: inventory-db
        app.kubernetes.io/version: "0.1.0"
        app.kubernetes.io/component: database
        app.kubernetes.io/part-of: skyline
    spec:
      containers:
        - name: inventory-db
          image: idos2002/skyline-inventory-db:0.1.0
          env:
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: inventory-db-config
                  key: user
                  optional: false
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: inventory-db-secret
                  key: password
                  optional: false
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: inventory-db-config
                  key: db_name
                  optional: false
              # Fixes permission issued as it cannot chown on the default directory,
              # as its owned by root.
              # See:
              #   - https://stackoverflow.com/questions/51200115/chown-changing-ownership-of-data-db-operation-not-permitted/51203031#51203031
              #   - https://stackoverflow.com/questions/51168558/how-to-mount-a-postgresql-volume-using-aws-ebs-in-kubernete
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          ports:
            - name: postgres
              containerPort: 5432
          volumeMounts:
            - name: inventory-db-data
              mountPath: /var/lib/postgresql/data
              subPath: pgdata
      volumes:
        - name: inventory-db-data
          persistentVolumeClaim:
            claimName: inventory-db
