apiVersion: v1
kind: Service
metadata:
  name: login
spec:
  selector:
    app.kubernetes.io/name: login
    app.kubernetes.io/version: "0.2.0"
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: skyline
  ports:
    - name: http
      port: 80
      targetPort: 8080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: login
  labels:
    name: login
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: login
      app.kubernetes.io/version: "0.2.0"
      app.kubernetes.io/component: backend
      app.kubernetes.io/part-of: skyline
  template:
    metadata:
      labels:
        app.kubernetes.io/name: login
        app.kubernetes.io/version: "0.2.0"
        app.kubernetes.io/component: backend
        app.kubernetes.io/part-of: skyline
    spec:
      containers:
        - name: login
          image: idos2002/skyline-login:0.2.0
          envFrom:
            - configMapRef:
                name: login-config
                optional: false
          env:
            - name: SKYLINE_PNR_DB_URL
              valueFrom:
                secretKeyRef:
                  name: pnr-db-secret
                  key: full_db_uri
                  optional: false
            - name: SKYLINE_PNR_DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: pnr-db-config
                  key: db_name
                  optional: false
            - name: SKYLINE_PNR_DB_COLLECTION_NAME
              valueFrom:
                configMapKeyRef:
                  name: pnr-db-config
                  key: pnr_collection_name
            - name: SKYLINE_ACCESS_TOKEN_SECRET
              valueFrom:
                secretKeyRef:
                  name: access-token-secret
                  key: access_token_secret
                  optional: false
          ports:
            - name: http
              containerPort: 8080
