apiVersion: v1
kind: Service
metadata:
  name: pnr-db
spec:
  selector:
    app.kubernetes.io/name: pnr-db
    app.kubernetes.io/version: "0.1.0"
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: skyline
  ports:
    - name: postgres
      port: 27017
      targetPort: 27017

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pnr-db
  labels:
    name: pnr-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: pnr-db
      app.kubernetes.io/version: "0.1.0"
      app.kubernetes.io/component: database
      app.kubernetes.io/part-of: skyline
  template:
    metadata:
      labels:
        app.kubernetes.io/name: pnr-db
        app.kubernetes.io/version: "0.1.0"
        app.kubernetes.io/component: database
        app.kubernetes.io/part-of: skyline
    spec:
      containers:
        - name: pnr-db
          image: idos2002/skyline-pnr-db:0.1.0
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: pnr-db-config
                  key: user
                  optional: false
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pnr-db-secret
                  key: password
                  optional: false
            - name: MONGO_INITDB_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: pnr-db-config
                  key: db_name
                  optional: false
          ports:
            - name: postgres
              containerPort: 27017
