apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
spec:
  selector:
    app.kubernetes.io/name: rabbitmq
    app.kubernetes.io/version: "0.1.0"
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: skyline
  ports:
    - name: amqp
      port: 5672
      targetPort: 5672
    - name: management
      port: 15672
      targetPort: 15672

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  labels:
    name: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: rabbitmq
      app.kubernetes.io/version: "0.1.0"
      app.kubernetes.io/component: backend
      app.kubernetes.io/part-of: skyline
  template:
    metadata:
      labels:
        app.kubernetes.io/name: rabbitmq
        app.kubernetes.io/version: "0.1.0"
        app.kubernetes.io/component: backend
        app.kubernetes.io/part-of: skyline
    spec:
      hostname: skyline-rabbitmq
      containers:
        - name: rabbitmq
          image: rabbitmq:3.9.13-management
          env:
            - name: RABBITMQ_NODE_PORT
              valueFrom:
                configMapKeyRef:
                  name: rabbitmq-config
                  key: amqp_port
                  optional: false
            - name: RABBITMQ_DEFAULT_USER
              valueFrom:
                configMapKeyRef:
                  name: rabbitmq-config
                  key: user
                  optional: false
            - name: RABBITMQ_DEFAULT_PASS
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: password
                  optional: false
            - name: RABBITMQ_DEFAULT_VHOST
              valueFrom:
                configMapKeyRef:
                  name: rabbitmq-config
                  key: vhost
                  optional: false
          ports:
            - name: amqp
              containerPort: 5672
            - name: management
              containerPort: 15672
