apiVersion: apps/v1
kind: Deployment
metadata:
  name: ticketing
  labels:
    name: ticketing
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: ticketing
      app.kubernetes.io/version: "0.1.0"
      app.kubernetes.io/component: backend
      app.kubernetes.io/part-of: skyline
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ticketing
        app.kubernetes.io/version: "0.1.0"
        app.kubernetes.io/component: backend
        app.kubernetes.io/part-of: skyline
    spec:
      containers:
        - name: ticketing
          image: idos2002/skyline-ticketing:0.1.0
          envFrom:
            - configMapRef:
                name: ticketing-config
                optional: false
          env:
            - name: SKYLINE_RABBITMQ_URI
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: full_uri
                  optional: false
            - name: SKYLINE_TICKET_EXCHANGE_NAME
              valueFrom:
                configMapKeyRef:
                  name: rabbitmq-config
                  key: ticket_exchange_name
                  optional: false
            - name: SKYLINE_TICKET_QUEUE_NAME
              valueFrom:
                configMapKeyRef:
                  name: rabbitmq-config
                  key: ticket_queue_name
                  optional: false
            - name: SKYLINE_TICKET_BOOKING_BINDING_KEY
              valueFrom:
                configMapKeyRef:
                  name: rabbitmq-config
                  key: ticket_binding_key
                  optional: false
            - name: SKYLINE_TICKET_BOOKING_MESSAGE_TYPE
              valueFrom:
                configMapKeyRef:
                  name: rabbitmq-config
                  key: ticket_booking_routing_key
                  optional: false
            - name: SKYLINE_EMAIL_EXCHANGE_NAME
              valueFrom:
                configMapKeyRef:
                  name: rabbitmq-config
                  key: email_exchange_name
                  optional: false
            - name: SKYLINE_EMAIL_TICKET_ROUTING_KEY
              valueFrom:
                configMapKeyRef:
                  name: rabbitmq-config
                  key: email_ticket_routing_key
                  optional: false
            - name: SKYLINE_DEAD_LETTER_EXCHANGE_NAME
              valueFrom:
                configMapKeyRef:
                  name: rabbitmq-config
                  key: dead_letter_exchange_name
                  optional: false
            - name: SKYLINE_DEAD_LETTER_ROUTING_KEY
              valueFrom:
                configMapKeyRef:
                  name: rabbitmq-config
                  key: dead_letter_ticket_booking_routing_key
                  optional: false
            - name: SKYLINE_PNR_DB_URI
              valueFrom:
                secretKeyRef:
                  name: pnr-db-secret
                  key: full_db_uri
                  optional: false
            - name: SKYLINE_PNR_DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: pnr-db-config
                  key: db_name
                  optional: false
            - name: SKYLINE_PNR_DB_COLLECTION_NAME
              valueFrom:
                configMapKeyRef:
                  name: pnr-db-config
                  key: pnr_collection_name
          ports:
            - name: http
              containerPort: 80
