apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pnr-db
  labels:
    app.kubernetes.io/name: pnr-db
    app.kubernetes.io/version: "0.1.0"
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: skyline
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
