CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE airport (
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    iata_code text NOT NULL,
    -- Check if it is a valid airport iata code, e.g. TLV, LAX, etc.
    CHECK (iata_code ~ '\A[A-Z]{3}\Z'),
    icao_code text NOT NULL,
    -- Check if it is a valid airport icao code, e.g. LLBG, KLAX, etc.
    CHECK (icao_code ~ '\A[A-Z]{4}\Z'),
    airport_name text NOT NULL,
    subdivision_code text NOT NULL,
    -- Check if it is a valid ISO 3166-2 subdivision code, e.g. IL-M, US-CA, etc.
    CHECK (subdivision_code ~ '\A[A-Z]{2}-[A-Z0-9]{1,3}\Z'),
    city text NOT NULL,
    geo_location geography(point) NOT NULL,
    UNIQUE (iata_code, icao_code),
);

CREATE TABLE service (
    service_number integer PRIMARY KEY,
    origin_airport_id integer NOT NULL REFERENCES airport (id),
    destination_airport_id integer NOT NULL REFERENCES airport (id),
    UNIQUE (origin_airport_id, destination_airport_id),
);

CREATE TABLE aircraft_model (
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    icao_code text NOT NULL,
    -- Check if it is a valid aircraft icao code, e.g. A5, B487, etc.
    CHECK (icao_code ~ '\A[A-Z0-9]{2,4}\Z'),
    iata_code text NOT NULL,
    -- Check if it is a valid aircraft iata code, e.g. A4F, 313, etc.
    CHECK (iata_code ~ '\A[A-Z0-9]{3}\Z'),
    model_name text NOT NULL,
    UNIQUE (icao_code, iata_code),
);

CREATE TABLE flight (
    id uuid PRIMARY KEY DEFAULT uuid_generate_v1(),
    service_id integer NOT NULL REFERENCES service (service_number),
    departure_terminal text NOT NULL,
    departure_utc_time timestamptz NOT NULL,
    arrival_terminal text NOT NULL,
    arrival_utc_time timestamptz NOT NULL,
    CHECK (departure_utc_time < arrival_utc_time),
    aircraft_model_id integer NOT NULL REFERENCES aircraft_model (id),
);

CREATE TYPE cabin_class AS ENUM ('E', 'B', 'F');

CREATE TABLE booked_seat (
    id uuid PRIMARY KEY DEFAULT uuid_generate_v1(),
    flight_id uuid NOT NULL REFERENCES flight (id),
    cabin_class cabin_class NOT NULL,
    seat_row integer NOT NULL CHECK (seat_row > 0),
    seat_column text NOT NULL,
    -- Check if the seat's column is a single uppercase letter (A-Z).
    CHECK (seat_column ~ '\A[A-Z]\Z'),
    UNIQUE (flight_id, seat_row, seat_column)
);

CREATE TABLE seat_map (
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    aircraft_model_id integer REFERENCES aircraft_model (id),
    cabin_class cabin_class NOT NULL,
    start_row integer NOT NULL CHECK (start_row > 0),
    end_row integer NOT NULL CHECK (end_row > 0),
    CHECK (start_row <= end_row),
    column_layout text NOT NULL,
    -- Check if column layout is in the correct form, e.g. ABC-EF-GHI, ABC, ABC-DEF, etc.)
    CHECK (column_layout ~ '\A[A-Z]+(?:-[A-Z]+)*\Z'),
    UNIQUE (aircraft_model_id, start_row, end_row),
);
